In [4]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [5]:
df =pd.read_csv(r'C:\Users\USER\Downloads\spotify_dataset.csv')
user_df = pd.read_csv(r'C:\Users\USER\Downloads\user_listening_history.csv')

In [3]:
df.head()

,title,artist,genre,danceability,energy,valence,tempo,acousticness,speechiness
0,Synthetic_Hip-Hop_23,Synthetic,Hip-Hop,0.7269,0.3737,0.6478,104.8750,0.0666,0.0951
1,Synthetic_Country_46,Synthetic,Country,0.4749,0.5808,0.3868,132.1218,0.6463,0.0430
2,Synthetic_Electronic_48,Synthetic,Electronic,0.4778,0.7228,0.3313,130.8892,0.0449,0.0257
3,Synthetic_Pop_39,Synthetic,Pop,0.5276,0.6226,0.3166,105.0044,0.2273,0.0741
4,Synthetic_Rock_24,Synthetic,Rock,0.5567,0.8816,0.2481,155.2690,0.1499,0.0420

In [6]:
user_df.head()

  customer_id                    title  listened
0    CUST_001     Synthetic_Hip-Hop_23         0
1    CUST_001     Synthetic_Country_46         0
2    CUST_001  Synthetic_Electronic_48         0
3    CUST_001         Synthetic_Pop_39         1
4    CUST_001        Synthetic_Rock_24         0

In [8]:
df[['title','genre','danceability','energy','valence','tempo','acousticness','speechiness']]

,title,genre,danceability,energy,valence,tempo,acousticness,speechiness
0,Synthetic_Hip-Hop_23,Hip-Hop,0.7269,0.3737,0.6478,104.8750,0.0666,0.0951
1,Synthetic_Country_46,Country,0.4749,0.5808,0.3868,132.1218,0.6463,0.0430
2,Synthetic_Electronic_48,Electronic,0.4778,0.7228,0.3313,130.8892,0.0449,0.0257
3,Synthetic_Pop_39,Pop,0.5276,0.6226,0.3166,105.0044,0.2273,0.0741
4,Synthetic_Rock_24,Rock,0.5567,0.8816,0.2481,155.2690,0.1499,0.0420
...,...,...,...,...,...,...,...,...
333,Synthetic_Rock_1,Rock,0.5068,0.7954,0.3935,172.4717,0.0178,0.0812
334,Synthetic_Pop_34,Pop,0.6294,0.6388,0.6408,148.9646,0.1936,0.0629
335,Synthetic_Hip-Hop_19,Hip-Hop,0.5407,0.4485,0.2380,61.6596,0.0522,0.2225
336,Synthetic_R&B_33,R&B,0.6149,0.5940,0.1919,143.9710,0.4005,0.0464
337,Synthetic_Hip-Hop_15,Hip-Hop,0.5799,0.5188,0.5647,133.1047,0.1476,0.0711

In [ ]:
full_df =  user_df.merge(df[['title','genre','danceability','energy','valence','tempo','acousticness','speechiness']],on=)

TypeError: DataFrame.merge() missing 1 required positional argument: 'right'

In [ ]:
full_df.head()

In [ ]:
full_df.select_dtypes(exclude='0').columns

In [ ]:
num_